
CREATE USER user1onmysqld2 IDENTIFIED BY 'mysqlpasswd';
GRANT REPLICATION SLAVE, REPLICATION CLIENT ON *.* TO user1onmysqld2;
FLUSH PRIVILEGES;

CREATE USER user3onmysqld2 IDENTIFIED BY 'mysqlpasswd';
GRANT REPLICATION SLAVE, REPLICATION CLIENT ON *.* TO user3onmysqld2;
FLUSH PRIVILEGES;

DROP DATABASE IF EXISTS testdb2;
CREATE DATABASE testdb2;
USE testdb2;
CREATE TABLE tb1(tb1col VARCHAR(10));
CREATE TABLE tb2(tb2col VARCHAR(10));

STOP SLAVE;
CHANGE REPLICATION FILTER REPLICATE_DO_DB=(testdb, testdb3);

CHANGE MASTER TO MASTER_HOST='mysqld', MASTER_PORT=3306, MASTER_AUTO_POSITION=1, MASTER_HEARTBEAT_PERIOD=60 FOR CHANNEL 'ch1';
START SLAVE USER='user2onmysqld1' PASSWORD='mysqlpasswd' FOR CHANNEL 'ch1';

CHANGE MASTER TO MASTER_HOST='mysqld3', MASTER_PORT=3306, MASTER_AUTO_POSITION=1, MASTER_HEARTBEAT_PERIOD=60 FOR CHANNEL 'ch3';
START SLAVE USER='user2onmysqld3' PASSWORD='mysqlpasswd' FOR CHANNEL 'ch3';
