CREATE USER user2onmysqld1 IDENTIFIED BY 'mysqlpasswd';
GRANT REPLICATION SLAVE, REPLICATION CLIENT ON *.* TO user2onmysqld1;
FLUSH PRIVILEGES;

CREATE USER user3onmysqld1 IDENTIFIED BY 'mysqlpasswd';
GRANT REPLICATION SLAVE, REPLICATION CLIENT ON *.* TO user3onmysqld1;
FLUSH PRIVILEGES;

DROP DATABASE IF EXISTS testdb;
CREATE DATABASE testdb;
USE testdb;
CREATE TABLE tb1(tb1col VARCHAR(10));
CREATE TABLE tb2(tb2col VARCHAR(10));

